### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by dogyoonlee** [Srameo/LE3D#1]
Thank you for your awesome work!

I'm really interested in your research.

When do you plan to release the code?

**Comment by Srameo** [comment]
Thank you for your recognition! We plan to release our code and interactive viewer next month.

**Comment by dogyoonlee** [comment]
@Srameo Great! I'm looking forward to your code being published!

**Comment by Srameo** [comment]
Apologies for the delay 😢 ; we are currently occupied with other tasks. 
So plan changed, we anticipate being able to release it before September 25th.

**Comment by Srameo** [comment]
Sorry that it took me some time to open source our code  😢, cause we try to release all the viewer, editor and code at once!

Now we have released our code, viewer and even a editor! Thanks for all your attention!
